# Generated by Django 4.2.3 on 2023-07-19 19:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_name', models.CharField(max_length=30, verbose_name='Brand')),
                ('Brand_icon', models.ImageField(upload_to='brand')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, verbose_name='Category')),
                ('category_icon', models.ImageField(upload_to='category')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Created_At')),
                ('update_at', models.DateField(auto_now_add=True, verbose_name='Update_At')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30, verbose_name='Product')),
                ('product_type', models.CharField(max_length=30, verbose_name='Type')),
                ('product_image', models.ImageField(upload_to='products/', verbose_name='Image')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Price')),
                ('product_size', models.CharField(max_length=30, verbose_name='Size')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Created_At')),
                ('update_at', models.DateField(auto_now_add=True, verbose_name='Update_At')),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('love', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'unique_together': {('customer', 'product')},
                'index_together': {('customer', 'product')},
            },
        ),
    ]
