# Generated by Django 4.2.3 on 2023-07-19 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_customer_favourite_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='love',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
