# Generated by Django 4.2.3 on 2023-07-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_favourite_love'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
